apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: execbox

resources:
  - namespace.yaml
  - rbac.yaml
  # Uncomment to apply resource quotas
  # - resourcequota.yaml

commonLabels:
  app.kubernetes.io/name: execbox
  app.kubernetes.io/managed-by: execbox-cloud
